dect v2
H13U1999/anbot-obj-detection pull request #6
Opened 2023-08-27 14:51 UTC by H13U1999

change torch hub down load to local

2023-08-27 14:53 UTC, bannnn511 requested changes
please put domain url in env

2023-08-28 06:30 UTC, H13U1999 commented
> please put domain url in env
okay bro

2023-08-29 10:56 UTC, H13U1999 commented
done bro @bannnn511

2023-08-29 10:56 UTC, bannnn511 approved these changes

2023-08-29 10:57 UTC, merged